# Generated by Django 5.1.1 on 2024-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, default='user_photos/profile.jpg', null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
