# Generated by Django 5.1.1 on 2024-10-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_photo_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
