# Generated by Django 5.1.1 on 2024-10-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='conpassword',
        ),
    ]
