# Generated by Django 5.1.1 on 2024-10-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_conpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_photo',
        ),
    ]
