# Generated by Django 5.1.1 on 2024-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_city_user_country_user_pincode_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
