# Generated by Django 5.1.1 on 2024-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_country_alter_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
