# Generated by Django 5.1.1 on 2024-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
