# Generated by Django 5.1.1 on 2024-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('book_price', models.CharField(blank=True, max_length=100, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_pics/')),
            ],
        ),
    ]
