# Generated by Django 5.1.1 on 2024-10-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
