# Generated by Django 5.1.1 on 2024-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_review_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
