# Generated by Django 5.1.1 on 2024-10-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_review_id_alter_review_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
