# Generated by Django 5.1.1 on 2024-10-13 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
